#pragma once
#define RECV -1
//#define FRIENDLIST 0
#define SIGNUP 1
#define LOGIN 2
#define LOGOUT 3
#define FRIENDLIST 0//隐藏bug除了0都不行
#define ADDFRIEND 5
#define DELETEFRIEND 6
#define AGREEADDFRIEND 7
#define REFUSEADDFRIEND 8
#define BLOCKFRIEND 9
#define RESTOREFRIEND 10
#define VIEWONLINESTATUS 11
#define CHATWITHFRIEND 12
#define UNREADMESSAGE 13
#define ADDGROUP 14
#define CREATEGROUP 15
#define SENDMSG 16
#define EXITCHAT 17
#define GROUPLIST 18
#define MEMBERLIST 19
#define DELETEGROUP 20
#define APPLYLIST 21
#define AGREEADDMEMBER 22
#define REFUSEADDMEMBER 23
#define DELETEMEMBER 24
#define ADDMANAGER 25
#define DELETEMANAGER 26
#define DISSOLVEGROUP 27


// ANSI 转义码设置文本颜色
#define L_GREEN "\033[1;32m"
#define NONE "\033[0m"
#define L_WHITE "\033[1;37m"